### ISSUE TITLE
Epic: avatar modifications for orthoverse-prismarine

### ISSUE THREAD

**Issue by kf106** [kf106/orthoverse-prismarine#83]
This requires coordination between orthoverse-avatar (currently in branch kf106/directCapes) and orthoverse-prismarine (currently in branch kf106/delayLogin

 - [x] #82 options setting for the avatars api root URI
 - [x] #81 ensure login with wallet does not connect to world until successful
 - [x] #76 invisible players (should be resolved incidentally to other issues)
 - [x] #67 multiple requests to load cape (should be resolved incidentally to other issues)
 - [x] #44 reload player entities if name, ski or cape changes

**Comment by kf106** [comment]
This requires a total rethink.

- use player.entity.skin.default to store the address, and player.entity.skin.cape to store whether the address is validated. This ensures that everything is transmitted correctly.

- when a user tries to connect using a new address, store the name and address in the orthoverse-avatars database.

- add an addressFromName function to orthoverse-avatars to allow reverse lookup

**Comment by kf107** [comment]
Completed with Avatars alpha release

**Comment by kf106** [comment]
Some of the bullet list items were not feasible, however the basic functionality is implemented Avatars alpha
